### This is the project of Web Scraping With pandas
this is the site we are scraping: https://football-data.co.uk/data.php

In [1]:
import pandas as pd

In [4]:
df_premier21 = pd.read_csv('https://football-data.co.uk/mmz4281/2122/E0.csv')

In [5]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [8]:
df_premier21.rename(columns={'FTHG':'home_goals', 'FTAG':'away_goals'}, inplace=True)

In [9]:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [10]:
leauges = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []
for a in leauges:
    df=pd.read_csv('https://football-data.co.uk/mmz4281/2122/'+ a +'.csv', encoding='unicode_escape')
    frames.append(df)

In [11]:
len(frames)

5

In [14]:
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

In [18]:
all_frames = []

for a in leauges:
    for b in range(15,21):
        year=str(b)+str(b+1)
        df=pd.read_csv('https://football-data.co.uk/mmz4281/'+year+'/'+ a +'.csv', encoding='unicode_escape')
        df.insert(1, 'season', f"Season {b}")
        all_frames.append(df)

In [17]:
len(all_frames)

30

In [19]:
all_frames[14]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E2,Season 17,05/08/17,Bradford,Blackpool,2,1,H,1,1,...,1.64,16,-0.75,1.86,1.81,2.08,2.04,1.69,3.97,5.50
1,E2,Season 17,05/08/17,Bury,Walsall,1,0,H,1,0,...,1.79,16,-0.50,2.09,2.03,1.87,1.82,2.02,3.55,4.03
2,E2,Season 17,05/08/17,Charlton,Bristol Rvs,1,0,H,1,0,...,1.89,16,-0.25,2.07,2.02,1.89,1.83,2.19,3.66,3.39
3,E2,Season 17,05/08/17,Doncaster,Gillingham,0,0,D,0,0,...,1.88,16,-0.50,1.83,1.79,2.11,2.06,1.69,3.96,5.45
4,E2,Season 17,05/08/17,Fleetwood Town,Rotherham,2,0,H,1,0,...,1.75,16,-0.25,2.00,1.94,1.98,1.91,2.20,3.38,3.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,Season 17,05/05/18,Rochdale,Charlton,1,0,H,0,0,...,1.73,18,-0.25,1.86,1.81,2.06,2.01,1.92,3.89,3.98
548,E2,Season 17,05/05/18,Rotherham,Blackpool,1,0,H,0,0,...,1.91,18,-0.25,2.20,2.11,1.80,1.74,2.14,3.79,3.34
549,E2,Season 17,05/05/18,Scunthorpe,Bradford,1,1,D,0,0,...,1.81,18,-0.50,1.93,1.86,2.01,1.96,1.92,3.68,4.21
550,E2,Season 17,05/05/18,Shrewsbury,Milton Keynes Dons,0,1,A,0,0,...,1.77,17,-0.75,2.12,2.03,1.84,1.80,1.76,3.84,4.98
551,E2,Season 17,05/05/18,Southend,Bristol Rvs,0,0,D,0,0,...,1.98,19,-0.25,2.03,1.95,1.95,1.87,2.23,3.78,3.16