In [1]:
print("Hellow")

Hellow

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\suuas'

In [4]:
os.listdir()

['-1.14-windows.xml',
 '.AndroidStudio3.4',
 '.arduinoIDE',
 '.bashrc',
 '.bash_history',
 '.bash_profile',
 '.cache',
 '.config',
 '.console-ninja',
 '.copilot',
 '.docker',
 '.eclipse',
 '.gitconfig',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.lesshst',
 '.librarymanager',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.node_repl_history',
 '.nvm',
 '.ollama',
 '.p2',
 '.python_history',
 '.redhat',
 '.sao',
 '.ssh',
 '.streamlit',
 '.templateengine',
 '.thumbnails',
 '.VirtualBox',
 '.vscode',
 '.vscode-shared',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'CrossDevice',
 'Documents',
 'eclipse',
 'eclipse-workspace',
 'Favorites',
 'HELLOWORLS.C',
 'Links',
 'Local Settings',
 'My Documents',
 'My project',
 'My project (1)',
 'MyApp',
 'myenv',
 'NetHood',
 'New folder',
 'npm-cache',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{89a8eefa-10fe-11f0-84f3-8c4d6e0e5c8c}.TxR.0.regtrans-ms',
 'NTUSER.DAT{89a8eefa-10fe-11f0-84f3-8c4d6e0e5c8c}.TxR.1.regtrans-ms',
 'NTUSER.DAT{89a8eefa-10fe-11f0-84f3-8c4d6e0e5c8c}.TxR.2.regtrans-ms',
 'NTUSER.DAT{89a8eefa-10fe-11f0-84f3-8c4d6e0e5c8c}.TxR.blf',
 'NTUSER.DAT{89a8eefb-10fe-11f0-84f3-8c4d6e0e5c8c}.TM.blf',
 'NTUSER.DAT{89a8eefb-10fe-11f0-84f3-8c4d6e0e5c8c}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{89a8eefb-10fe-11f0-84f3-8c4d6e0e5c8c}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Postman',
 'Postman Agent',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Source',
 'Start Menu',
 'Suyash Rusia',
 'Templates',
 'Untitled.ipynb']

In [45]:
import pandas as pd

In [3]:
a = [[1,2],[3,4],[5,6]]
print(a)

[[1, 2], [3, 4], [5, 6]]

In [4]:
df = pd.DataFrame(a, index=["row1", "row2", "row3"], columns=['col1', 'col2'])
print(df)

      col1  col2
row1     1     2
row2     3     4
row3     5     6

In [5]:
state = ['MP', 'MH', 'KA']
city = [4, 14, 9]

In [6]:
dict_city = {'States': state, 'Cities': city}

In [7]:
df_city = pd.DataFrame(dict_city)

In [8]:
df_city

  States  Cities
0     MP       4
1     MH      14
2     KA       9

In [9]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [11]:
#Methords Commonly used
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [13]:
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [14]:
df_exams.head(11)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52

In [15]:
df_exams.tail(11)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [21]:
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [22]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [17]:
#Attributes Commonly used
df_exams.shape

(1000, 8)

In [18]:
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [19]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [20]:
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [23]:
#Functions Commonly used
len(df_exams)

1000

In [26]:
max(df_exams.index)

999

In [27]:
min(df_exams.index)

0

In [28]:
type(df_exams)

pandas.core.frame.DataFrame

In [29]:
round(df_exams, 2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [30]:
#Selecting Columns
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [31]:
type(df_exams['gender'])

pandas.core.series.Series

In [32]:
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [33]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [34]:
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [35]:
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [37]:
#Selecting Multiple Columns
df_exams[['gender', 'math score', 'lunch']]

     gender  math score         lunch
0    female          72      standard
1    female          69      standard
2    female          90      standard
3      male          47  free/reduced
4      male          76      standard
..      ...         ...           ...
995  female          88      standard
996    male          62  free/reduced
997  female          59  free/reduced
998  female          68      standard
999  female          77  free/reduced

[1000 rows x 3 columns]

In [38]:
type(df_exams[['gender', 'math score', 'lunch']])

pandas.core.frame.DataFrame

In [43]:
#Adding New Column to Dataframe
df_exams['total score'] = round((df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3, 2)

In [44]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

In [46]:
import numpy as np

In [49]:
#Creating an array of range 1000 here 0 will be included and 1000 won't
language_score = np.arange(0,1000)

In [51]:
#Length of array created using np
len(language_score)

1000

In [52]:
#Here 1 is min number less than 100 is max and 1000 is the size of array needed
english_score = np.random.randint(1,100, size=1000)

In [53]:
df_exams['english score'] = english_score

In [54]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67,91
1,female,group C,some college,standard,completed,69,90,88,82.33,84
2,female,group B,master's degree,standard,none,90,95,93,92.67,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33,98
4,male,group C,some college,standard,none,76,78,75,76.33,80
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00,25
996,male,group C,high school,free/reduced,none,62,55,55,57.33,85
997,female,group C,high school,free/reduced,completed,59,71,65,65.00,36
998,female,group D,some college,standard,completed,68,78,77,74.33,4
999,female,group D,some college,free/reduced,none,77,86,86,83.00,8

In [58]:
df_exams['total score'] = round((df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'] + df_exams['english score'])/4, 2)

In [59]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score
0,female,group B,bachelor's degree,standard,none,72,72,74,77.25,91
1,female,group C,some college,standard,completed,69,90,88,82.75,84
2,female,group B,master's degree,standard,none,90,95,93,76.25,27
3,male,group A,associate's degree,free/reduced,none,47,57,44,61.50,98
4,male,group C,some college,standard,none,76,78,75,77.25,80
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,76.75,25
996,male,group C,high school,free/reduced,none,62,55,55,64.25,85
997,female,group C,high school,free/reduced,completed,59,71,65,57.75,36
998,female,group D,some college,standard,completed,68,78,77,56.75,4
999,female,group D,some college,free/reduced,none,77,86,86,64.25,8

In [60]:
#using assign() to add multiple columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [67]:
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score1, index=np.arange(0, 1000))

In [64]:
#This is only a copy orignal Dataframe is not changed
df_exams.assign(score1=series1, score2=series2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
1,female,group C,some college,standard,completed,69,90,88,82.75,84,57,57
2,female,group B,master's degree,standard,none,90,95,93,76.25,27,47,47
3,male,group A,associate's degree,free/reduced,none,47,57,44,61.50,98,34,34
4,male,group C,some college,standard,none,76,78,75,77.25,80,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,76.75,25,51,51
996,male,group C,high school,free/reduced,none,62,55,55,64.25,85,42,42
997,female,group C,high school,free/reduced,completed,59,71,65,57.75,36,55,55
998,female,group D,some college,standard,completed,68,78,77,56.75,4,93,93
999,female,group D,some college,free/reduced,none,77,86,86,64.25,8,19,19

In [65]:
#Dataframe reflects changes when we assign using = operator
df_exams = df_exams.assign(score1=series1, score2=series2)

In [66]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
1,female,group C,some college,standard,completed,69,90,88,82.75,84,57,57
2,female,group B,master's degree,standard,none,90,95,93,76.25,27,47,47
3,male,group A,associate's degree,free/reduced,none,47,57,44,61.50,98,34,34
4,male,group C,some college,standard,none,76,78,75,77.25,80,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,76.75,25,51,51
996,male,group C,high school,free/reduced,none,62,55,55,64.25,85,42,42
997,female,group C,high school,free/reduced,completed,59,71,65,57.75,36,55,55
998,female,group D,some college,standard,completed,68,78,77,56.75,4,93,93
999,female,group D,some college,free/reduced,none,77,86,86,64.25,8,19,19

In [68]:
#Adding new column using insert() this adds into orignal Dataframe here 1 is index in columns test is name and series1 is values
df_exams.insert(1, 'test', series1)

In [69]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
0,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
1,female,57,group C,some college,standard,completed,69,90,88,82.75,84,57,57
2,female,47,group B,master's degree,standard,none,90,95,93,76.25,27,47,47
3,male,34,group A,associate's degree,free/reduced,none,47,57,44,61.50,98,34,34
4,male,68,group C,some college,standard,none,76,78,75,77.25,80,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,51,group E,master's degree,standard,completed,88,99,95,76.75,25,51,51
996,male,42,group C,high school,free/reduced,none,62,55,55,64.25,85,42,42
997,female,55,group C,high school,free/reduced,completed,59,71,65,57.75,36,55,55
998,female,93,group D,some college,standard,completed,68,78,77,56.75,4,93,93
999,female,19,group D,some college,free/reduced,none,77,86,86,64.25,8,19,19

In [71]:
#Calculate total sum, count, mean, std, min, max these are operations done on columns
df_exams['math score'].sum()

np.int64(66089)

In [73]:
df_exams['math score'].count()

np.int64(1000)

In [74]:
df_exams['math score'].mean()

np.float64(66.089)

In [75]:
df_exams['math score'].std()

np.float64(15.16308009600945)

In [76]:
df_exams['math score'].min()

np.int64(0)

In [77]:
df_exams['math score'].max()

np.int64(100)

In [78]:
df_exams.describe()

,test,math score,reading score,writing score,total score,english score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,50.667000,66.08900,69.169000,68.054000,63.488750,50.643000,50.667000,50.667000
std,28.232059,15.16308,14.600192,15.195657,13.219652,29.665023,28.232059,28.232059
min,1.000000,0.00000,17.000000,10.000000,13.250000,1.000000,1.000000,1.000000
25%,26.000000,57.00000,59.000000,57.750000,54.500000,23.000000,26.000000,26.000000
50%,51.500000,66.00000,70.000000,69.000000,64.000000,53.000000,51.500000,51.500000
75%,75.000000,77.00000,79.000000,79.000000,72.500000,77.000000,75.000000,75.000000
max,99.000000,100.00000,100.000000,100.000000,94.500000,99.000000,99.000000,99.000000

In [79]:
#Oprations are done in rows
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [82]:
#Average of all the scores
df_exams['total score'] = round((df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'] + df_exams['english score'])/4, 2)

In [83]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
0,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
1,female,57,group C,some college,standard,completed,69,90,88,82.75,84,57,57
2,female,47,group B,master's degree,standard,none,90,95,93,76.25,27,47,47
3,male,34,group A,associate's degree,free/reduced,none,47,57,44,61.50,98,34,34
4,male,68,group C,some college,standard,none,76,78,75,77.25,80,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,51,group E,master's degree,standard,completed,88,99,95,76.75,25,51,51
996,male,42,group C,high school,free/reduced,none,62,55,55,64.25,85,42,42
997,female,55,group C,high school,free/reduced,completed,59,71,65,57.75,36,55,55
998,female,93,group D,some college,standard,completed,68,78,77,56.75,4,93,93
999,female,19,group D,some college,free/reduced,none,77,86,86,64.25,8,19,19

In [85]:
#Count value counting using value_count()
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [86]:
#Normalize=True meaning it gives us ratio/percentage
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [89]:
df_exams['parental level of education'].value_counts(normalize=True)

parental level of education
some college          0.226
associate's degree    0.222
high school           0.196
some high school      0.179
bachelor's degree     0.118
master's degree       0.059
Name: proportion, dtype: float64

In [90]:
#Sort Columns Ascending By Default These are only a copy
df_exams.sort_values('math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
59,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74
980,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
17,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
787,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
145,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,male,90,group A,some college,standard,completed,100,96,86,88.50,72,90,90
625,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
962,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
458,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
916,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70

In [91]:
#Sorting Columns by Decending
df_exams.sort_values('math score', ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
451,female,15,group E,some college,standard,none,100,92,97,72.75,2,15,15
458,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
962,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
149,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
623,male,90,group A,some college,standard,completed,100,96,86,88.50,72,90,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
787,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
17,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
980,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
59,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [92]:
#Sorting Columns by multiple columns 
df_exams.sort_values(['math score', 'reading score'], ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
149,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
458,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
916,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
962,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
625,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
787,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
17,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
980,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
59,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [93]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
0,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
1,female,57,group C,some college,standard,completed,69,90,88,82.75,84,57,57
2,female,47,group B,master's degree,standard,none,90,95,93,76.25,27,47,47
3,male,34,group A,associate's degree,free/reduced,none,47,57,44,61.50,98,34,34
4,male,68,group C,some college,standard,none,76,78,75,77.25,80,68,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,51,group E,master's degree,standard,completed,88,99,95,76.75,25,51,51
996,male,42,group C,high school,free/reduced,none,62,55,55,64.25,85,42,42
997,female,55,group C,high school,free/reduced,completed,59,71,65,57.75,36,55,55
998,female,93,group D,some college,standard,completed,68,78,77,56.75,4,93,93
999,female,19,group D,some college,free/reduced,none,77,86,86,64.25,8,19,19

In [94]:
#Sorting Columns by multiple columns inplace meaning Updating orignal Dataframe
df_exams.sort_values(['math score', 'reading score'], ascending=False, inplace=True)

In [95]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
149,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
458,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
916,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
962,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
625,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
787,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
17,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
980,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
59,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [96]:
#Sorting Columns with key function
df_exams.sort_values('race/ethnicity', key=lambda col:col.str.lower())

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
741,female,98,group A,associate's degree,free/reduced,none,37,57,56,41.50,16,98,98
151,male,93,group A,bachelor's degree,standard,none,77,67,68,58.25,21,93,93
811,male,17,group A,high school,free/reduced,none,45,47,49,40.50,21,17,17
112,male,23,group A,associate's degree,standard,none,54,53,47,42.25,15,23,23
25,male,76,group A,master's degree,free/reduced,none,73,74,72,63.75,36,76,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,male,4,group E,some college,standard,none,68,72,65,63.50,49,4,4
915,female,89,group E,some college,standard,none,68,70,66,68.25,69,89,89
592,male,91,group E,bachelor's degree,standard,none,68,68,64,67.75,71,91,91
479,male,85,group E,associate's degree,standard,none,76,71,67,58.00,18,85,85
517,female,70,group E,some college,standard,completed,66,74,73,70.50,69,70,70

In [97]:
import random

In [99]:
#Create New Index
new_index = np.arange(0,1000)

In [100]:
#Shuffle Indexes
random.shuffle(new_index)

In [101]:
#Create new column with new index
df_exams['new_index'] = new_index

In [102]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2,new_index
149,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85,119
458,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18,500
916,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70,877
962,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51,10
625,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60,881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96,792
787,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73,683
17,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11,793
980,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66,517
59,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74,989

In [103]:
#Setting New index only a copy
df_exams.set_index('new_index')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [105]:
df_exams.set_index('new_index', inplace=True)

In [106]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [107]:
df_exams.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
0,female,20,group E,some high school,free/reduced,none,72,79,77,62.50,22,20,20
1,male,10,group D,master's degree,standard,none,82,82,74,72.00,50,10,10
2,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
3,female,89,group B,high school,standard,completed,58,70,68,55.75,27,89,89
4,male,76,group B,high school,standard,none,60,68,60,67.75,83,76,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,male,48,group C,high school,standard,completed,53,52,49,55.75,69,48,48
996,female,77,group D,master's degree,free/reduced,completed,61,71,78,72.50,80,77,77
997,male,66,group D,associate's degree,free/reduced,none,53,54,48,57.00,73,66,66
998,female,73,group A,master's degree,standard,none,50,53,58,56.25,64,73,73
999,female,5,group C,some college,standard,completed,71,71,80,57.25,7,5,5

In [108]:
#Rename Columns only a copy
df_exams.rename(columns={'gender':'Gender'})

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [109]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [110]:
#Updated the renamed
df_exams=df_exams.rename(columns={'gender':'Gender'})

In [111]:
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [113]:
#Renameing Multiple columns
df_exams.rename(columns={'math score':'MS', 'reading score':'RS', 'writing score':'WS'}, inplace=True)

In [114]:
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
119,male,85,group E,associate's degree,free/reduced,completed,100,100,93,88.50,61,85,85
500,female,18,group E,bachelor's degree,standard,none,100,100,100,76.75,7,18,18
877,male,70,group E,bachelor's degree,standard,completed,100,100,100,84.00,36,70,70
10,female,51,group E,associate's degree,standard,none,100,100,100,91.50,66,51,51
881,male,60,group D,some college,standard,completed,100,97,99,86.75,51,60,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,female,96,group C,some college,free/reduced,none,22,39,33,30.75,29,96,96
683,female,73,group B,some college,standard,none,19,38,32,25.00,11,73,73
793,female,11,group B,some high school,free/reduced,none,18,32,28,28.50,36,11,11
517,female,66,group B,high school,free/reduced,none,8,24,23,30.75,68,66,66
989,female,74,group C,some high school,free/reduced,none,0,17,10,13.25,26,74,74

In [116]:
df_exams.sort_index(inplace=True)

In [117]:
df_exams

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
0,female,20,group E,some high school,free/reduced,none,72,79,77,62.50,22,20,20
1,male,10,group D,master's degree,standard,none,82,82,74,72.00,50,10,10
2,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
3,female,89,group B,high school,standard,completed,58,70,68,55.75,27,89,89
4,male,76,group B,high school,standard,none,60,68,60,67.75,83,76,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,male,48,group C,high school,standard,completed,53,52,49,55.75,69,48,48
996,female,77,group D,master's degree,free/reduced,completed,61,71,78,72.50,80,77,77
997,male,66,group D,associate's degree,free/reduced,none,53,54,48,57.00,73,66,66
998,female,73,group A,master's degree,standard,none,50,53,58,56.25,64,73,73
999,female,5,group C,some college,standard,completed,71,71,80,57.25,7,5,5

In [118]:
#Renameing Indexes
df_exams.rename(index={0:'A', 1:'B', 2:'C'}, inplace=True)

In [120]:
df_exams.head()

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,total score,english score,score1,score2
new_index,,,,,,,,,,,,,
A,female,20,group E,some high school,free/reduced,none,72,79,77,62.50,22,20,20
B,male,10,group D,master's degree,standard,none,82,82,74,72.00,50,10,10
C,female,73,group B,bachelor's degree,standard,none,72,72,74,77.25,91,73,73
3,female,89,group B,high school,standard,completed,58,70,68,55.75,27,89,89
4,male,76,group B,high school,standard,none,60,68,60,67.75,83,76,76