In [1]:
import pandas as pd

In [9]:
df1=pd.DataFrame({'id':['A','B','C','D'],
              'age': [25,27,24,22]
             })
df2=pd.DataFrame({'id':['C','D','E','F'],
                  'job':['Accountant', 'Developer','Founder','Unemployed']
                 })

In [10]:
df1

  id  age
0  A   25
1  B   27
2  C   24
3  D   22

In [11]:
df2

  id         job
0  C  Accountant
1  D   Developer
2  E     Founder
3  F  Unemployed

In [17]:
# sample here shows inner joins overlaping based on ids
df1.merge(df2, on='id', how='inner')

  id  age         job
0  C   24  Accountant
1  D   22   Developer

In [70]:
df_m=pd.read_csv('IMDb movies.csv', low_memory=False)
df_r=pd.read_csv('IMDb ratings.csv')

In [71]:
df_m= df_m[['imdb_title_id', 'title', 'year', 'genre', 'country', ]]
df_r=df_r[['imdb_title_id', 'total_votes', 'mean_vote']]

In [20]:
# inner is default
df_m.merge(df_r, on='imdb_title_id')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [32]:
# outer just merge it all
df1.merge(df2, on='id', how='outer')

  id   age         job
0  A  25.0         NaN
1  B  27.0         NaN
2  C  24.0  Accountant
3  D  22.0   Developer
4  E   NaN     Founder
5  F   NaN  Unemployed

In [33]:
df_m.merge(df_r, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [34]:
df1.merge(df2,on='id',how='outer', indicator=True)

  id   age         job      _merge
0  A  25.0         NaN   left_only
1  B  27.0         NaN   left_only
2  C  24.0  Accountant        both
3  D  22.0   Developer        both
4  E   NaN     Founder  right_only
5  F   NaN  Unemployed  right_only

In [35]:
# Exclusive full join all intersecting values are dropped
df1.merge(df2,on='id',how='outer', indicator=True).query('_merge=="left_only" or _merge=="right_only"')

  id   age         job      _merge
0  A  25.0         NaN   left_only
1  B  27.0         NaN   left_only
4  E   NaN     Founder  right_only
5  F   NaN  Unemployed  right_only

In [38]:
df_m.merge(df_r,on='imdb_title_id', how='outer', indicator=True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [39]:
df_m.merge(df_r,on='imdb_title_id', how='outer', indicator=True).query('_merge=="left_only" or _merge=="right_only"')

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

In [42]:
df1.merge(df2, on='id',how='left')

  id  age         job
0  A   25         NaN
1  B   27         NaN
2  C   24  Accountant
3  D   22   Developer

In [44]:
sam=df_m.sample(frac=0.5)

In [46]:
mersam=sam.merge( df_r, on='imdb_title_id', how='left')

In [49]:
mersam.shape

(42928, 7)

In [50]:
mersam

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0798423,Kariseuma talchulgi,2006,Comedy,South Korea,316,6.4
1,tt1772850,Exit 33,2011,Horror,USA,215,4.0
2,tt0135520,"Laterna, ftoheia kai garyfallo",1957,"Comedy, Drama",Greece,629,6.9
3,tt0099554,UFO - Pioggia mortale,1990,"Action, Sci-Fi, Thriller","USA, Australia, Yugoslavia, UK",141,4.0
4,tt5357556,The Premier - Rapimento e ricatto,2016,Thriller,Belgium,2325,6.3
...,...,...,...,...,...,...,...
42923,tt0105322,Scanners 3,1991,"Action, Horror, Sci-Fi","Canada, Thailand, USA",1819,4.5
42924,tt0058123,Crisantemi per un delitto,1964,"Crime, Drama, Romance",France,1818,7.1
42925,tt0382383,Yuva,2004,"Action, Drama, Thriller",India,8381,7.5
42926,tt2570292,Du Bunui Gyulhonsikgwa Han Bunui Jangryesik,2012,"Comedy, Romance",South Korea,375,6.6
42927,tt0218798,I 12 mesi,1956,"Animation, Family, Fantasy",Soviet Union,1050,7.5

In [51]:
# Outer is set to how only when exclusive full left or right is needed
df1.merge(df2,on='id', how='outer', indicator=True).query('_merge=="left_only"')

  id   age  job     _merge
0  A  25.0  NaN  left_only
1  B  27.0  NaN  left_only

In [73]:
copy=df_m.copy()
for a in range (0,1000):
    copy.iloc[a,0]='tt1234567890'

In [59]:
df_m.iloc[0,0]='ttshutdown'

In [76]:
df_m.iloc[999]

imdb_title_id                  tt0021492
title                   True to the Navy
year                                1930
genre            Action, Comedy, Romance
country                              USA
Name: 999, dtype: object

In [82]:
exleft=copy.merge(df_r,on='imdb_title_id',how='outer',indicator=True).query('_merge=="left_only"')

In [83]:
exleft.shape

(1000, 8)

In [85]:
df1.merge(df2, on='id', how='right')

  id   age         job
0  C  24.0  Accountant
1  D  22.0   Developer
2  E   NaN     Founder
3  F   NaN  Unemployed

In [96]:
ri=sam.merge(df_r.sample(frac=0.3), on='imdb_title_id', how='right')

In [97]:
ri

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt2870406,NaN,NaN,NaN,NaN,233,4.7
1,tt0462215,NaN,NaN,NaN,NaN,144,5.9
2,tt0132380,NaN,NaN,NaN,NaN,735,6.8
3,tt1176142,NaN,NaN,NaN,NaN,1616,2.5
4,tt0078389,I 39 scalini,1978,"Crime, History, Mystery",UK,2218,6.8
...,...,...,...,...,...,...,...
25751,tt0120577,Studio 54,1998,"Drama, Music",USA,31181,5.9
25752,tt0182736,NaN,NaN,NaN,NaN,151,5.6
25753,tt0452668,Pterodactyl,2005,"Action, Adventure, Horror",USA,2245,3.5
25754,tt0117887,NaN,NaN,NaN,NaN,61290,7.1
25755,tt1988805,NaN,NaN,NaN,NaN,226,4.3

In [98]:
ri.shape

(25756, 7)

In [99]:
exleft=copy.merge(df_r, on='imdb_title_id', how='right', indicator=True).query('_merge=="right_only"')

In [100]:
exleft

    imdb_title_id title year genre country  total_votes  mean_vote      _merge
0       tt0000009   NaN  NaN   NaN     NaN          154        5.9  right_only
1       tt0000574   NaN  NaN   NaN     NaN          589        6.3  right_only
2       tt0001892   NaN  NaN   NaN     NaN          188        6.0  right_only
3       tt0002101   NaN  NaN   NaN     NaN          446        5.3  right_only
4       tt0002130   NaN  NaN   NaN     NaN         2237        6.9  right_only
..            ...   ...  ...   ...     ...          ...        ...         ...
995     tt0021472   NaN  NaN   NaN     NaN          128        5.8  right_only
996     tt0021483   NaN  NaN   NaN     NaN          160        6.6  right_only
997     tt0021484   NaN  NaN   NaN     NaN          106        7.2  right_only
998     tt0021486   NaN  NaN   NaN     NaN          172        6.2  right_only
999     tt0021492   NaN  NaN   NaN     NaN          103        7.0  right_only

[1000 rows x 8 columns]

In [101]:
exleft.shape

(1000, 8)