In [43]:
import pandas as pd
import numpy as np

In [19]:
df_laptops = pd.read_csv('C:/Users/suuas/OneDrive/Desktop/Codes/Python/Pandas practice/Filter Data/LaptopPrice.csv', encoding='unicode_escape')

In [20]:
#Creates an new column based on a specific condition such as price
df_laptops['Price_tier']=np.where(df_laptops['Price_euros']>2000,'Expensive','Cheap')

In [21]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [22]:
df_laptops['Price_tier'].value_counts()

Price_tier
Cheap        1166
Expensive     137
Name: count, dtype: int64

In [23]:
#Exercise for display size classification big or small
df_laptops.insert(5,'Size',np.where(df_laptops['Inches']>15.0,'Dekai','Chisai'))

In [26]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Dekai,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [27]:
df_laptops.value_counts('Size')

Size
Dekai     835
Chisai    468
Name: count, dtype: int64

### Filter Data based on multiple conditions
#### Useing & and |

In [34]:
#Here We are seeing the companies and number of laptops by them which are expensive and less than 15 inches in size
df_laptops[(df_laptops['Price_tier']=='Expensive') & (df_laptops['Size']=='Chisai')].value_counts('Company')

Company
Lenovo       20
HP           11
Dell          5
Razer         3
Toshiba       2
Apple         1
Google        1
Microsoft     1
Name: count, dtype: int64

In [35]:
df_laptops[(df_laptops['Price_tier']=='Expensive') & ((df_laptops['Company']=='Apple') | (df_laptops['Company']=='Dell'))].value_counts('Company')

Company
Dell     34
Apple     5
Name: count, dtype: int64

In [65]:
#Creating a condition column based on more than two conditions/choices
conditions = [
    df_laptops['Price_euros']>3000.00,
    (df_laptops['Price_euros']>2000.00) & (df_laptops['Price_euros']<=3000.00),
    (df_laptops['Price_euros']>800.00) & (df_laptops['Price_euros']<=2000.00),
    df_laptops['Price_euros']<=800.00
]

values = ['Too Expensive', 'Expensive', 'Affordable', 'Cheap']

In [68]:
df_laptops['Price_category']=np.select(conditions,values,default='')

In [69]:
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category
0,1,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Affordable
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Affordable
2,3,HP,250 G6,Notebook,15.6,Dekai,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Affordable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Chisai,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap,Cheap
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Chisai,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Cheap,Affordable
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Cheap
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Cheap
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Cheap,Cheap

In [70]:
df_laptops['Price_category'].value_counts()

Price_category
Affordable       655
Cheap            511
Expensive        118
Too Expensive     19
Name: count, dtype: int64

In [79]:
#Creating a condition column based on more than two conditions/choices
conditions = [
    (df_laptops['Price_euros']>3000.00) & (df_laptops['Size']=='Chisai'),
    (df_laptops['Price_euros']>3000.00) & (df_laptops['Size']=='Dekai'),
    ((df_laptops['Price_euros']>2000.00) & (df_laptops['Price_euros']<=3000.00))& (df_laptops['Size']=='Chisai'),
    ((df_laptops['Price_euros']>2000.00) & (df_laptops['Price_euros']<=3000.00))& (df_laptops['Size']=='Dekai'),
    ((df_laptops['Price_euros']>800.00) & (df_laptops['Price_euros']<=2000.00))& (df_laptops['Size']=='Chisai'),
    ((df_laptops['Price_euros']>800.00) & (df_laptops['Price_euros']<=2000.00))& (df_laptops['Size']=='Dekai'),
    df_laptops['Price_euros']<=800.00
]

values = ['Takai', 'Kangaerareru', 'Kangaerareru','Saiteki','Saiteki','Yasui','Yasui']

In [80]:
df_laptops['Actual_value']=np.select(conditions,values,default='')

In [81]:
df_laptops

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
0,1,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Affordable,Saiteki
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Affordable,Saiteki
2,3,HP,250 G6,Notebook,15.6,Dekai,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Cheap,Yasui
3,4,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Expensive,Saiteki
4,5,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Affordable,Saiteki
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Chisai,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap,Cheap,Yasui
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Chisai,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Cheap,Affordable,Saiteki
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Cheap,Yasui
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Cheap,Yasui
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.00,Cheap,Cheap,Yasui

In [82]:
#Look for Apple and HP in a specific company column using isin() methord
df_laptops['Company'].isin(['Apple','Lenovo'])

0        True
1        True
2       False
3        True
4        True
        ...
1298     True
1299     True
1300     True
1301    False
1302    False
Name: Company, Length: 1303, dtype: bool

In [83]:
#Filter useing isin()
df_laptops[df_laptops['Company'].isin(['Apple','Lenovo'])]

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
0,1,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Affordable,Saiteki
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Affordable,Saiteki
3,4,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Expensive,Saiteki
4,5,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Affordable,Saiteki
6,7,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.2GHz,16GB,256GB Flash Storage,Intel Iris Pro Graphics,Mac OS X,2.04kg,2139.97,Expensive,Expensive,Saiteki
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1286,1304,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Cheap,Yasui
1293,1311,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 6700HQ 2.6GHz,8GB,1TB HDD,Nvidia GeForce GTX 960M,Windows 10,2.6kg,899.00,Cheap,Affordable,Yasui
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Chisai,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Cheap,Cheap,Yasui
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Chisai,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Cheap,Affordable,Saiteki
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Cheap,Yasui

In [84]:
# Multiple filters based on multiple condition using isin() methord
filter1=df_laptops['TypeName'].isin(['Notebook','Ultrabook'])
filter2=df_laptops['Company'].isin(['Apple','HP'])

In [87]:
df_laptops[filter1 & filter2]

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
0,1,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap,Affordable,Saiteki
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Affordable,Saiteki
2,3,HP,250 G6,Notebook,15.6,Dekai,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap,Cheap,Yasui
3,4,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive,Expensive,Saiteki
4,5,Apple,MacBook Pro,Ultrabook,13.3,Chisai,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap,Affordable,Saiteki
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1273,1291,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Cheap,Yasui
1280,1298,HP,Pavilion 15-AW003nv,Notebook,15.6,Dekai,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap,Cheap,Yasui
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Cheap,Yasui
1294,1312,HP,Pavilion 15-AW003nv,Notebook,15.6,Dekai,Full HD 1920x1080,AMD A9-Series 9410 2.9GHz,6GB,1.0TB Hybrid,AMD Radeon R7 M440,Windows 10,2.04kg,549.99,Cheap,Cheap,Yasui
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Cheap,Cheap,Yasui

In [89]:
#Check for Duplicate values useing duplicated() methord
df_laptops.duplicated('laptop_ID')

0       False
1       False
2       False
3       False
4       False
        ...
1298    False
1299    False
1300    False
1301    False
1302    False
Length: 1303, dtype: bool

In [94]:
duplicated=df_laptops.duplicated(['Product','TypeName','Inches'])

In [96]:
df_laptops[duplicated].sort_values(['Product','TypeName','Inches'])

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0,Cheap,Cheap,Yasui
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Dekai,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0,Cheap,Cheap,Yasui
1098,1113,HP,250 G5,Notebook,15.6,Dekai,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,1TB HDD,Intel HD Graphics 405,Windows 10,1.96kg,500.0,Cheap,Cheap,Yasui
1170,1188,HP,250 G5,Notebook,15.6,Dekai,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.96kg,679.0,Cheap,Cheap,Yasui
10,11,HP,250 G6,Notebook,15.6,Dekai,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.9,Cheap,Cheap,Yasui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,Chisai,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg,928.0,Cheap,Affordable,Saiteki
826,835,Asus,ZenBook Flip,2 in 1 Convertible,13.3,Chisai,Touchscreen / Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1358.0,Cheap,Affordable,Saiteki
1275,1293,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Chisai,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0,Cheap,Cheap,Yasui
1289,1307,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Chisai,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0,Cheap,Cheap,Yasui
676,684,Asus,Zenbook 3,Ultrabook,14.0,Chisai,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1135.0,Cheap,Affordable,Saiteki

### Find the Cheapest and Most Expensive Laptops from each Companies

In [104]:
df_laptops.sort_values(['Company', 'Price_euros'])

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,Chisai,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.00,Cheap,Cheap,Yasui
290,295,Acer,Chromebook C910-C2ST,Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,16GB SSD,Intel HD Graphics,Chrome OS,2.19kg,199.00,Cheap,Cheap,Yasui
1102,1117,Acer,Chromebook 15,Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,4GB,16GB SSD,Intel HD Graphics,Chrome OS,2.20kg,209.00,Cheap,Cheap,Yasui
695,703,Acer,TravelMate B117-M,Netbook,11.6,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,269.00,Cheap,Cheap,Yasui
1198,1216,Acer,Aspire 3,Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.00,Cheap,Cheap,Yasui
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,195,Vero,K147 (N3350/4GB/32GB/FHD/W10),Notebook,14.0,Chisai,IPS Panel Full HD 1920x1080,Intel Celeron Dual Core N3350 1.1GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.3kg,260.00,Cheap,Cheap,Yasui
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,Chisai,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00,Cheap,Affordable,Saiteki
192,196,Xiaomi,Mi Notebook,Ultrabook,13.3,Chisai,IPS Panel Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.3kg,999.90,Cheap,Affordable,Saiteki
184,188,Xiaomi,Mi Notebook,Notebook,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i5 8250U 1.6GHz,8GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1199.00,Cheap,Affordable,Yasui
514,521,Xiaomi,Mi Notebook,Notebook,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95,Cheap,Affordable,Yasui

In [115]:
duplef=df_laptops.sort_values(['Company', 'Price_euros']).duplicated('Company',keep='first')
duplel=df_laptops.sort_values(['Company', 'Price_euros']).duplicated('Company',keep='last')

In [116]:
df_laptops[~duplef]

C:\Users\suuas\AppData\Local\Temp\ipykernel_6748\1743623183.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_laptops[~duplef]

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
1,2,Apple,Macbook Air,Ultrabook,13.3,Chisai,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap,Affordable,Saiteki
20,21,Asus,Vivobook E200HA,Netbook,11.6,Chisai,1366x768,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,0.98kg,191.90,Cheap,Cheap,Yasui
30,31,Chuwi,"LapBook 15.6""",Notebook,15.6,Dekai,Full HD 1920x1080,Intel Atom x5-Z8300 1.44GHz,4GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.89kg,244.99,Cheap,Cheap,Yasui
159,163,Toshiba,Satellite Pro,Notebook,15.6,Dekai,1366x768,Intel Core i3 6006U 2.2GHz,4GB,500GB HDD,Intel HD Graphics 520,Windows 10,2.1kg,447.00,Cheap,Cheap,Yasui
170,174,Huawei,MateBook X,Ultrabook,13.0,Chisai,IPS Panel Full HD 2160x1440,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.05kg,1349.00,Cheap,Affordable,Saiteki
340,346,Dell,Inspiron 3552,Notebook,15.6,Dekai,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Linux,2.2kg,274.90,Cheap,Cheap,Yasui
430,437,Samsung,Chromebook 3,Netbook,11.6,Chisai,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,16GB Flash Storage,Intel HD Graphics 400,Chrome OS,1.15kg,269.00,Cheap,Cheap,Yasui
457,464,Microsoft,Surface Laptop,Ultrabook,13.5,Chisai,Touchscreen 2256x1504,Intel Core M m3-7Y30 2.2GHz,4GB,128GB SSD,Intel HD Graphics 615,Windows 10 S,1.252kg,989.00,Cheap,Affordable,Saiteki
472,479,Google,Pixelbook (Core,Ultrabook,12.3,Chisai,Touchscreen 2400x1600,Intel Core i5 7Y57 1.2GHz,8GB,128GB SSD,Intel HD Graphics 615,Chrome OS,1.1kg,1275.00,Cheap,Affordable,Saiteki
626,633,Mediacom,SmartBook 140,Notebook,14.0,Chisai,Full HD 1920x1080,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg,239.00,Cheap,Cheap,Yasui
877,888,Xiaomi,Mi Notebook,Ultrabook,13.3,Chisai,IPS Panel Full HD 1920x1080,Intel Core i5 6200U 2.3GHz,8GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.28kg,935.00,Cheap,Affordable,Saiteki
909,922,LG,Gram 14Z970,Ultrabook,14.0,Chisai,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,0.98kg,1899.00,Cheap,Affordable,Saiteki
983,997,Fujitsu,LifeBook A556,Notebook,15.6,Dekai,1366x768,Intel Core i5 6200U 2.3GHz,4GB,256GB SSD,Intel HD Graphics 520,Windows 10,2.3kg,649.00,Cheap,Cheap,Yasui
1117,1132,Razer,Blade Stealth,Ultrabook,12.5,Chisai,Touchscreen / 4K Ultra HD 3840x2160,Intel Core i7 6500U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.25kg,1029.00,Cheap,Affordable,Saiteki
1120,1135,Vero,V131 (X5-Z8350/4GB/32GB/FHD/W10),Notebook,13.3,Chisai,Full HD 1920x1080,Intel Atom X5-Z8350 1.44GHz,4GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.35kg,196.00,Cheap,Cheap,Yasui
1169,1187,MSI,PL60 7RD,Gaming,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,8GB,1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.2kg,839.00,Cheap,Affordable,Yasui
1215,1233,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,Chisai,1366x768,Intel Celeron Dual Core 3205U 1.5GHz,2GB,32GB SSD,Intel HD Graphics,Chrome OS,1.3kg,174.00,Cheap,Cheap,Yasui
1268,1286,HP,Stream 11-Y000na,Netbook,11.6,Chisai,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Windows 10,1.17kg,209.00,Cheap,Cheap,Yasui
1272,1290,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Chisai,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.00,Cheap,Cheap,Yasui

In [117]:
df_laptops[~duplel]

C:\Users\suuas\AppData\Local\Temp\ipykernel_6748\2759629546.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_laptops[~duplel]

,laptop_ID,Company,Product,TypeName,Inches,Size,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier,Price_category,Actual_value
17,18,Apple,MacBook Pro,Ultrabook,15.4,Dekai,IPS Panel Retina Display 2880x1800,Intel Core i7 2.9GHz,16GB,512GB SSD,AMD Radeon Pro 560,macOS,1.83kg,2858.00,Expensive,Expensive,Saiteki
177,181,MSI,GT80S 6QF-074US,Gaming,18.4,Dekai,Full HD 1920x1080,Intel Core i7 6920HQ 2.9GHz,32GB,512GB SSD + 1TB HDD,Nvidia GTX 980 SLI,Windows 10,4.4kg,2799.00,Expensive,Expensive,Saiteki
191,195,Vero,K147 (N3350/4GB/32GB/FHD/W10),Notebook,14.0,Chisai,IPS Panel Full HD 1920x1080,Intel Celeron Dual Core N3350 1.1GHz,4GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.3kg,260.00,Cheap,Cheap,Yasui
196,200,Razer,Blade Pro,Gaming,17.3,Dekai,4K Ultra HD / Touchscreen 3840x2160,Intel Core i7 7820HK 2.9GHz,32GB,1TB SSD,Nvidia GeForce GTX 1080,Windows 10,3.49kg,6099.00,Expensive,Too Expensive,Kangaerareru
214,219,Huawei,MateBook X,Ultrabook,13.0,Chisai,IPS Panel Full HD 2160x1440,Intel Core i7 7500U 2.7GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.05kg,1499.00,Cheap,Affordable,Saiteki
421,428,Chuwi,LapBook 12.3,Notebook,12.3,Chisai,IPS Panel Retina Display 2736x1824,Intel Celeron Quad Core N3450 1.1GHz,6GB,64GB Flash Storage,Intel HD Graphics 500,Windows 10,1.4kg,449.00,Cheap,Cheap,Yasui
437,444,Google,Pixelbook (Core,Ultrabook,12.3,Chisai,Touchscreen 2400x1600,Intel Core i7 7Y75 1.3GHz,16GB,512GB SSD,Intel HD Graphics 615,Chrome OS,1.1kg,2199.00,Expensive,Expensive,Kangaerareru
449,456,Microsoft,Surface Laptop,Ultrabook,13.5,Chisai,Touchscreen 2256x1504,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10 S,1.25kg,2589.00,Expensive,Expensive,Kangaerareru
491,498,Toshiba,Portege X30-D-10L,Ultrabook,13.3,Chisai,Full HD / Touchscreen 1920x1080,Intel Core i7 7500U 2.7GHz,32GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.05kg,2799.00,Expensive,Expensive,Kangaerareru
514,521,Xiaomi,Mi Notebook,Notebook,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,16GB,256GB SSD,Nvidia GeForce MX150,No OS,1.95kg,1399.95,Cheap,Affordable,Yasui
580,587,Mediacom,SmartBook Edge,Notebook,14.0,Chisai,IPS Panel Full HD 1920x1080,Intel Celeron Quad Core N3450 1.1GHz,4GB,32GB SSD,Intel HD Graphics 500,Windows 10,1.45kg,389.00,Cheap,Cheap,Yasui
610,617,Lenovo,Thinkpad P51,Notebook,15.6,Dekai,IPS Panel 4K Ultra HD 3840x2160,Intel Xeon E3-1535M v6 3.1GHz,32GB,1TB SSD,Nvidia Quadro M2200M,Windows 10,2.5kg,4899.00,Expensive,Too Expensive,Kangaerareru
623,630,Fujitsu,LifeBook A557,Notebook,15.6,Dekai,1366x768,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg,799.00,Cheap,Cheap,Yasui
678,686,LG,Gram 15Z975,Ultrabook,15.6,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 8550U 1.8GHz,8GB,512GB SSD,Intel HD Graphics 620,Windows 10,1.09kg,2299.00,Expensive,Expensive,Saiteki
723,731,Dell,Alienware 17,Gaming,17.3,Dekai,4K Ultra HD 3840x2160,Intel Core i7 7700HQ 2.8GHz,32GB,1TB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.36kg,3659.40,Expensive,Too Expensive,Kangaerareru
749,758,HP,Zbook 17,Workstation,17.3,Dekai,IPS Panel Full HD 1920x1080,Intel Xeon E3-1535M v5 2.9GHz,16GB,256GB SSD,Nvidia Quadro M2000M,Windows 7,3kg,4389.00,Expensive,Too Expensive,Kangaerareru
874,885,Samsung,Notebook 9,Ultrabook,15.0,Chisai,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,16GB,256GB SSD,Nvidia GeForce 940MX,Windows 10,1.23kg,1849.00,Cheap,Affordable,Saiteki
1066,1081,Asus,ROG G701VO,Gaming,17.3,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 6820HK 2.7GHz,64GB,1TB SSD,Nvidia GeForce GTX 980,Windows 10,3.58kg,3975.00,Expensive,Too Expensive,Kangaerareru
1189,1207,Acer,Predator G9-793,Gaming,17.3,Dekai,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,16GB,256GB SSD + 1TB HDD,Nvidia GeForce GTX 1070,Windows 10,4.2kg,2599.00,Expensive,Expensive,Saiteki

In [122]:
# Delete/Drop Duplicates from the DF using drop_duplicates() methord
df_laptops.drop_duplicates('Company')[['Company','Price_euros']]

       Company  Price_euros
0        Apple      1339.69
2           HP       575.00
5         Acer       400.00
8         Asus      1495.00
13        Dell       498.90
18      Lenovo       499.00
30       Chuwi       244.99
58         MSI      2449.00
70   Microsoft      1089.00
143    Toshiba       602.00
170     Huawei      1349.00
184     Xiaomi      1199.00
191       Vero       260.00
196      Razer      6099.00
429   Mediacom       299.00
430    Samsung       269.00
437     Google      2199.00
567    Fujitsu       739.00
678         LG      2299.00

In [129]:
df_sorted=df_laptops.sort_values(['Company', 'Price_euros'])
df_sorted.drop_duplicates('Company',keep='first')[['Company', 'Price_euros']]

        Company  Price_euros
1215       Acer       174.00
1         Apple       898.94
20         Asus       191.90
30        Chuwi       244.99
340        Dell       274.90
983     Fujitsu       649.00
472      Google      1275.00
1268         HP       209.00
170      Huawei      1349.00
909          LG      1899.00
1272     Lenovo       229.00
1169        MSI       839.00
626    Mediacom       239.00
457   Microsoft       989.00
1117      Razer      1029.00
430     Samsung       269.00
159     Toshiba       447.00
1120       Vero       196.00
877      Xiaomi       935.00

In [130]:
df_sorted=df_laptops.sort_values(['Company', 'Price_euros'])
df_sorted.drop_duplicates('Company',keep='last')[['Company', 'Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
1066       Asus      3975.00
421       Chuwi       449.00
723        Dell      3659.40
623     Fujitsu       799.00
437      Google      2199.00
749          HP      4389.00
214      Huawei      1499.00
678          LG      2299.00
610      Lenovo      4899.00
177         MSI      2799.00
580    Mediacom       389.00
449   Microsoft      2589.00
196       Razer      6099.00
874     Samsung      1849.00
491     Toshiba      2799.00
191        Vero       260.00
514      Xiaomi      1399.95

In [134]:
df_sorted.drop_duplicates('Company',keep='last', inplace=True, ignore_index=True)

In [136]:
df_sorted[['Company', 'Price_euros']]

      Company  Price_euros
0        Acer      2599.00
1       Apple      2858.00
2        Asus      3975.00
3       Chuwi       449.00
4        Dell      3659.40
5     Fujitsu       799.00
6      Google      2199.00
7          HP      4389.00
8      Huawei      1499.00
9          LG      2299.00
10     Lenovo      4899.00
11        MSI      2799.00
12   Mediacom       389.00
13  Microsoft      2589.00
14      Razer      6099.00
15    Samsung      1849.00
16    Toshiba      2799.00
17       Vero       260.00
18     Xiaomi      1399.95

In [137]:
# unique() returns all the unique values in column/series
df_laptops['Company'].unique()

array(['Apple', 'HP', 'Acer', 'Asus', 'Dell', 'Lenovo', 'Chuwi', 'MSI',
       'Microsoft', 'Toshiba', 'Huawei', 'Xiaomi', 'Vero', 'Razer',
       'Mediacom', 'Samsung', 'Google', 'Fujitsu', 'LG'], dtype=object)

In [139]:
# nunique() returns number of unique values in column/series
df_laptops['Company'].nunique()

19