## Data Updation and Delete/Drop too

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('players_20.csv')

In [6]:
df = df.set_index('short_name')

In [7]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [9]:
df=df.iloc[:,2:9]

In [12]:
# Updated the specific location/field 
df.loc['L. Messi', 'height_cm'] = 173
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,173,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [13]:
# Updated the all location/field 
df.loc[:, 'height_cm'] = 173
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,173,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,173,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,173,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,173,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,173,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,173,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,173,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,173,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,173,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,173,78,China PR,Hebei China Fortune FC

In [14]:
df.iloc[-1,:]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         173
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [15]:
import numpy as np
df.iloc[-1,:]=np.nan
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,173.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,173.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,173.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,173.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,173.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,173.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,173.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,173.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,173.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.drop('L. Messi', axis=0, inplace=True)
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,173.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,173.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,173.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,173.0,74.0,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28.0,1991-06-28,173.0,70.0,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,173.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,173.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,173.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,173.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.drop(index='Pan Ximing', inplace=True)
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,173.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,173.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,173.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,173.0,74.0,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28.0,1991-06-28,173.0,70.0,Belgium,Manchester City
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20.0,1999-01-05,173.0,84.0,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22.0,1997-03-10,173.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,173.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,173.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,173.0,74.0,China PR,Shanghai Greenland Shenhua FC

In [21]:
df.drop('long_name', axis=1)

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Cristiano Ronaldo,34.0,1985-02-05,173.0,83.0,Portugal,Juventus
Neymar Jr,27.0,1992-02-05,173.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,26.0,1993-01-07,173.0,87.0,Slovenia,Atlético Madrid
E. Hazard,28.0,1991-01-07,173.0,74.0,Belgium,Real Madrid
K. De Bruyne,28.0,1991-06-28,173.0,70.0,Belgium,Manchester City
...,...,...,...,...,...,...
P. Martin,20.0,1999-01-05,173.0,84.0,Republic of Ireland,Waterford FC
Shao Shuai,22.0,1997-03-10,173.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,22.0,1997-01-01,173.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,19.0,2000-05-16,173.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,18.0,2000-08-02,173.0,74.0,China PR,Shanghai Greenland Shenhua FC

In [24]:
df.drop(columns=['long_name','age'])

,dob,height_cm,weight_kg,nationality,club
short_name,,,,,
Cristiano Ronaldo,1985-02-05,173.0,83.0,Portugal,Juventus
Neymar Jr,1992-02-05,173.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,1993-01-07,173.0,87.0,Slovenia,Atlético Madrid
E. Hazard,1991-01-07,173.0,74.0,Belgium,Real Madrid
K. De Bruyne,1991-06-28,173.0,70.0,Belgium,Manchester City
...,...,...,...,...,...
P. Martin,1999-01-05,173.0,84.0,Republic of Ireland,Waterford FC
Shao Shuai,1997-03-10,173.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,1997-01-01,173.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,2000-05-16,173.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,2000-08-02,173.0,74.0,China PR,Shanghai Greenland Shenhua FC