## Data Extraction using pandas
#### loc[row_lable,column_lable] and iloc[row_position,column_position] will be used

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('players_20.csv')

In [7]:
# Set index to names
df.set_index('short_name', inplace=True)

In [8]:
df

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shao Shuai,245006,https://sofifa.com/player/245006/shuai-shao/20...,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
Xiao Mingjie,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
Zhang Wei,252332,https://sofifa.com/player/252332/wei-zhang/20/...,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
Wang Haijian,251110,https://sofifa.com/player/251110/haijian-wang/...,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
Pan Ximing,233449,https://sofifa.com/player/233449/ximing-pan/20...,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [10]:
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [11]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [15]:
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [16]:
df.loc['L. Messi', 'height_cm']

np.int64(170)

In [18]:
# Here : is representing all row_lables/indexes
df.loc[:, 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [19]:
df.loc['L. Messi', :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [21]:
df.loc[['L. Messi', 'Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [22]:
df.loc[['L. Messi', 'Cristiano Ronaldo'], 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [23]:
df.loc['L. Messi',[ 'height_cm', 'weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [24]:
df.loc[['L. Messi', 'Cristiano Ronaldo'],[ 'height_cm', 'weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [26]:
# Using : and defining we want data from a:b a to b
df.loc[['L. Messi', 'Cristiano Ronaldo'], 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [27]:
df.index[:10]

Index(['L. Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'J. Oblak', 'E. Hazard',
       'K. De Bruyne', 'M. ter Stegen', 'V. van Dijk', 'L. Modrić',
       'M. Salah'],
      dtype='object', name='short_name')

In [28]:
df.loc['L. Messi':'M. Salah',['age','dob','height_cm','weight_kg','nationality','club']]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,27,1992-06-15,175,71,Egypt,Liverpool

In [29]:
df.loc['L. Messi':'M. Salah','age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,27,1992-06-15,175,71,Egypt,Liverpool

In [34]:
df.loc[df['height_cm']>180, 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...
P. Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [38]:
df.loc[(df['nationality']=='Argentina') & (df['height_cm']>180), 'age':'club'].head(10)

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
M. Icardi,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
F. Vázquez,30,1989-02-22,186,82,Argentina,Sevilla FC
J. Correa,24,1994-08-13,188,77,Argentina,Lazio
E. Andrada,28,1991-01-26,194,81,Argentina,Boca Juniors
W. Benítez,26,1993-01-19,191,91,Argentina,OGC Nice
E. Lamela,27,1992-03-04,184,80,Argentina,Tottenham Hotspur

In [39]:
# Selecting elements by using iloc[]
df.iloc[0]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [40]:
df.iloc[0,3]

np.int64(170)

In [41]:
df.iloc[1,4]

np.int64(83)

In [42]:
df.iloc[:,3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [43]:
df.iloc[0,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [44]:
df.iloc[[0,1],:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [45]:
df.iloc[[0,1],3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [46]:
df.iloc[0,[3,4]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [47]:
df.iloc[[0,1],[3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

In [50]:
# Here value after :7 is excluded
df.iloc[[0,1],1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [53]:
df.iloc[0:10, 1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,27,1992-06-15,175,71,Egypt,Liverpool

In [54]:
# iloc[] dose not take the df series as a parameter so we need to convert it into a list to give it to iloc[]
df.iloc[list(df['height_cm']>180), 1:5]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [59]:
df.iloc[list(df['height_cm']>180), 1:7].drop_duplicates('height_cm').sort_values('height_cm')

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
L. Suárez,32,1987-01-24,182,86,Uruguay,FC Barcelona
T. Kroos,29,1990-01-04,183,76,Germany,Real Madrid
Sergio Ramos,33,1986-03-30,184,82,Spain,Real Madrid
E. Cavani,32,1987-02-14,185,77,Uruguay,Paris Saint-Germain
T. Alderweireld,30,1989-03-02,186,81,Belgium,Tottenham Hotspur
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
Sergio Busquets,30,1988-07-16,189,76,Spain,FC Barcelona
L. Bonucci,32,1987-05-01,190,85,Italy,Juventus
Alisson,26,1992-10-02,191,91,Brazil,Liverpool
De Gea,28,1990-11-07,192,82,Spain,Manchester United
V. van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
Piqué,32,1987-02-02,194,85,Spain,FC Barcelona
W. Szczęsny,29,1990-04-18,195,90,Poland,Juventus
G. Donnarumma,20,1999-02-25,196,90,Italy,Milan
K. Casteels,27,1992-06-25,197,86,Belgium,VfL Wolfsburg
Naldo,36,1982-09-10,198,91,Brazil,AS Monaco
T. Courtois,27,1992-05-11,199,96,Belgium,Real Madrid
N. Pope,27,1992-04-19,200,76,England,Burnley
L. Kalinić,29,1990-04-03,201,99,Croatia,Aston Villa
V. Milinković-Savić,22,1997-02-20,202,92,Serbia,Standard de Liège
C. Pantilimon,32,1987-02-01,203,96,Romania,Nottingham Forest
T. Holý,27,1991-12-10,205,102,Czech Republic,Ipswich Town

In [63]:
df.iloc[list((df['height_cm']>180) & (df['nationality']=='England')) , 1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
H. Kane,25,1993-07-28,188,89,England,Tottenham Hotspur
D. Alli,23,1996-04-11,188,80,England,Tottenham Hotspur
K. Walker,29,1990-05-28,183,70,England,Manchester City
M. Rashford,21,1997-10-31,186,70,England,Manchester United
J. Stones,25,1994-05-28,188,70,England,Manchester City
...,...,...,...,...,...,...
C. Painter,17,2002-02-22,183,75,England,Grimsby Town
C. Pattison,18,2000-12-28,185,70,England,Milton Keynes Dons
G. Sykes-Kenworthy,19,1999-10-01,182,78,England,Bradford City
C. Heath,18,2000-12-11,188,78,England,Crewe Alexandra
S. Cartwright,18,2000-07-08,185,75,England,Peterborough United