### Sample Data Generation

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('players_20.csv')

In [5]:
df.set_index('short_name', inplace=True)

In [6]:
df=df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [12]:
# Sample(n) methord is used to extract n number of random elements 
# here random_state=99 gets us exact same n elements every time raandom_state is used to controle randomness
df['nationality'].sample(10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [22]:
# extract a certain percentage (2% here) of data frame using frac(fraction)
df.sample(frac=0.02, random_state=12)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen
M. Nadé,Mickaël Nadé,20,1999-03-04,188,80,France,AS Saint-Étienne
V. García,Víctor Hugo García Hernández,25,1994-06-11,178,71,Venezuela,Vitória Guimarães
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice
...,...,...,...,...,...,...,...
T. Kleindienst,Tim Kleindienst,23,1995-08-31,194,86,Germany,SC Freiburg
T. Röcher,Thorsten Röcher,28,1991-06-11,181,78,Austria,SK Sturm Graz
Lucas Piazon,Gustavo Lucas Domingues Piazon,25,1994-01-20,182,73,Brazil,Chelsea
W. Muzyk,Wojciech Muzyk,20,1998-11-07,196,83,Poland,Legia Warszawa
D. Marzino,Dario Marzino,22,1996-09-19,184,80,Switzerland,BSC Young Boys

In [24]:
# we can increase the sample by making frac>1 amd also write replace=True
df.sample(frac=1.234, replace=True)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
A. Hjulsager,Andrew Hjulsager,24,1995-01-15,177,73,Denmark,KV Oostende
T. Augello,Tommaso Augello,24,1994-08-30,180,70,Italy,Sampdoria
Eliseo Falcón,Eliseo Falcón Falcón,22,1997-02-11,183,80,Spain,Levante UD
F. Florio,Filippo Florio,23,1996-04-23,180,72,Italy,Pordenone
C. Nkunku,Christopher Nkunku,21,1997-11-14,179,72,France,RB Leipzig
...,...,...,...,...,...,...,...
Kang Min Soo,강민수 康敏寿,33,1986-02-14,186,76,Korea Republic,Ulsan Hyundai FC
S. Lusiusz,Sylwester Lusiusz,19,1999-09-18,185,75,Poland,Cracovia
J. Monreal,Josepablo Monreal,23,1996-04-01,190,76,Chile,Unión La Calera
N. Bazan,Nazareno Bazan,20,1999-03-08,184,74,Argentina,Vélez Sarsfield
M. Abdulrahman,Mohammed Abdulrahman,30,1989-02-04,173,60,United Arab Emirates,Al Ain FC

### Filter Datafram using Query() methord

In [27]:
# in query methord we need to write the condition in ''
df.query('age>34').head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [28]:
# this was our old filter methord it is also known as boolean slicing
df[df['age']>34].head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [29]:
# in query methord "" inside of '' is used for the purpose of diffrentiating between two conditions
# instaed of & we use "and" here
df.query('age>34 and nationality=="Italy"').head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC

In [35]:
df[(df['age']>34) & (df['nationality']=="Italy")].head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC

In [36]:
# not() operator is used to do the work of ~(!) 
df.query('not(age>34)').head(5)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [40]:
df[df['age']>~34].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [42]:
df.query('height_cm/100 > 1.8').head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool

In [55]:
df[(df['height_cm']/100)>1.8].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool

In [58]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
dtype: object

In [64]:
df = df.copy()
df['dob'] = df['dob'].astype('datetime64[ns]')

In [65]:
df.dtypes

long_name              object
age                     int64
dob            datetime64[ns]
height_cm               int64
weight_kg               int64
nationality            object
club                   object
dtype: object

In [70]:
df[df['dob'].dt.year > 1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [69]:
# using query
df.query("dob.dt.year > 1990")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### Apply() methord used to apply functions of numpy

In [73]:
# Numpy functionality is introduced inside the ()
import numpy as np
df['age'].apply(np.sqrt)

short_name
L. Messi             5.656854
Cristiano Ronaldo    5.830952
Neymar Jr            5.196152
J. Oblak             5.099020
E. Hazard            5.291503
                       ...
Shao Shuai           4.690416
Xiao Mingjie         4.690416
Zhang Wei            4.358899
Wang Haijian         4.242641
Pan Ximing           5.099020
Name: age, Length: 18278, dtype: float64

In [74]:
def calculate_bmi(datafram):
    return datafram['weight_kg']/(datafram['height_cm']/100)**2

In [75]:
df.apply(calculate_bmi, axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

## Lambda Function

In [76]:
# first lets see basic function
def sum_v(a,b):
    x= a+b
    return x

In [77]:
sum_v(2,4)

6

In [78]:
# now Lambda function
sum_lambda = lambda a,b:a+b

In [79]:
sum_lambda(3,4)

7

In [82]:
# We can use lambda func without a name here because we are only going to use it once
df['height_cm'].apply(lambda x:x/100)

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [83]:
df['long_name'].apply(lambda x:x.upper())

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [84]:
df['dob'].apply(lambda x:x.year)

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [86]:
df.apply(lambda x: x['weight_kg']/((x['height_cm']/100)**2), axis=1)

short_name
L. Messi             24.913495
Cristiano Ronaldo    23.735308
Neymar Jr            22.204082
J. Oblak             24.615211
E. Hazard            24.163265
                       ...
Shao Shuai           22.835010
Xiao Mingjie         21.066743
Zhang Wei            21.678807
Wang Haijian         21.621622
Pan Ximing           23.547881
Length: 18278, dtype: float64

### Copy of a dataframe using copy() methord

In [88]:
# in copy we have deep=True as default parameter
# this will allow the copy to be independent copy not just a holder pointing to orignal
dfc=df.copy()

In [89]:
df.loc['L. Messi', 'height_cm'] = 200

In [90]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,200,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [91]:
dfc

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [92]:
# by setting deep to false we can say that the new dfcopy is just pointing to orignal df it is not a new entity
dfcopy = df.copy(deep=False)
dfcopy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,200,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [93]:
df.loc['L. Messi', 'height_cm']=180

In [94]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [95]:
dfcopy

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [96]:
# We can also make copy by just assigning it with = operator it will be shallow meaning deep=False
df_new=df

In [98]:
df.loc['L. Messi', 'age'] = 23

In [99]:
df_new

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,23,1987-06-24,180,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC